nelmio_api_doc:
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)
  documentation:
    tags:
    - name: "Article"
      description: "Access to Articles"
    - name: "Category"
      description: "Access to Categories"
    info:
      title: Test Work Rest API
      version: 1.0.0
    securityDefinitions:
      basicAuth:
        type: basic
