version: '3.6'
services:
  nginx:
    image: nginx:latest
    networks:
      - app_network
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - .docker/nginx/conf/testwork.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:ro
    restart: unless-stopped
  php:
    build:
      context: .docker/php
    networks:
      - app_network
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal idekey=123"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    networks:
      - app_network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
networks:
  app_network:
    driver: bridge
